# Site
# repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ting Jiang
title: Computer Vision & Computer Graphics
email: tjhedlen@gmail.com
website: tjwork.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  tjwork
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: balazssandor
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links (https://fontawesome.com/icons?d=gallery&m=free)
additional_links:
- title: google scholar
  icon: fab fa-google
  url: https://scholar.google.com/citations?user=vwVneW4AAAAJ&hl=zh-CN

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Biography
about_profile_image: images/white_bg.png
about_content: | # this will include new lines to allow paragraphs
  I am a third-year graduate student of machine learning and computer vision under the supervision of 
  [Prof. Yiming Pi](https://www.researchgate.net/scientific-contributions/Yiming-Pi-13739828) and 
  [Prof. Zongjie Cao](https://www.researchgate.net/scientific-contributions/Zongjie-Cao-33269443) at University of Electronic Science and Technology of China (UESTC). 
  Meanwhile, I start my internship at SenseTime and Megvii Research since 2018. I am a Full time computer vision researcher at present in MEGVII. My research interests include Face recognition and detection, 
  Model compress, Autonomous driving, High dynaimc range image etc.
  
content:
  - title: Education & Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:      
      - layout: left
        title: M.Sc.
        # link: grubhub.com
        # link_text: grubhub.com
        # sub_title: 
        caption: Sept. 2016 - Jul. 2019
        description: | # this will include new lines to allow paragraphs
            ## **University of Electronic Science and Technology of China (UESTC)**
            Information and Communication Engineering <br />
            <mark>Thesis</mark> arget recognition, Target detection, Model compression.
      
      - layout: left
        title: B.E.
        # link: bmwgroup.com
        # link_text: bmwgroup.com
        # sub_title:  
        caption: Sept. 2011 - Jul. 2015
        description: | # this will include new lines to allow paragraphs
            
            ## **University of South China (USC)**
            Electronic Information Engineering <br />
            <mark>Thesis</mark> Electronic circuit system. 
                     
      - layout: left
        title: Internship
        # link: www.msg.group
        # link_text: msg.group
        # sub_title: 
        caption: May. 2018 - Dec. 2018
        description: | # this will include new lines to allow paragraphs
          ## **SenseTime Research**
          Intern <br />
          <mark>Feilds</mark> Face recognition and detection, Image and video retrieval.

      - layout: left
        title: Internship
        # link: www.msg.group
        # link_text: msg.group
        # sub_title: 
        caption:  Dec. 2018 - Jul. 2019
        description: | # this will include new lines to allow paragraphs
          ## **Megvii Research**
          Intern <br />
          <mark>Feilds</mark>  Autonomous driving, Intelligent cockpit, Behavior detection.
      
      - layout: left
        title: Full-time employee（FTE）
        # link: www.msg.group
        # link_text: msg.group
        # sub_title: 
        caption:  Jul. 2019 - Present
        description: | # this will include new lines to allow paragraphs
          ## **Megvii Research**
          Intern <br />
          <mark>Feilds</mark>  Computer graphics, High dynamic range image(HDR), etc.
            
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CVPR 2022
        # caption: 
        sub_title: <blue_mark>Under review</blue_mark>
        description: | # this will include new lines to allow paragraphs
          ## **HDRLUT: Unsupervised Learning 1D Lookup Tables for \\ High Dynamic Range Imaging**
          **Ting Jiang**, Chuan Wang, Xinpeng Li, Haoqiang Fan, Shuaicheng Liu 
          ![HDRLUT](./images/HDR.png)
          [[PDF](https://arxiv.org/pdf/2106.pdf)]
          [[Github](https://github.com/Hedlen/HDRLUT)]
          [Video: []]
          [BibTex]
        

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Driver Monitor System
        caption: Dec. 2018 - Jul. 2019
        sub_title: Major member
        description: | # this will include new lines to allow paragraphs
          I am responsible for designing a light-weighted end-to-end network running on an onboard chip to detect smoking, phoning, 
          and drinking in driving. Participated in the overall pipeline of algorithm development, including data collection, 
          data cleaning, algorithm development, and upgrading.
        video_path: images/DMS_smoke_demo1.mp4
        video_path1: images/DMS_smoke_demo2.mp4
        video_path2: images/DMS_phone_demo.mp4

      - layout: left
        title: High dynaimc range image(YUV or RAW)
        caption: Jul. 2019 - Mar. 2020
        sub_title: Algorithm Leader
        description: | # this will include new lines to allow paragraphs
          As the algorithm leader, there are currently 10 members in the team. The main direction is related to computer graphics, 
          including HDR, image enhancement, noise reduction, image alignment, dark light brightening, ghosting, super-segmentation, etc.
        image_path: images/HDR.png

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
theme: jekyll-theme-time-machine