# Site
# repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ting Jiang
title: Computer Vision & Computer Graphics
email: tjhedlen@gmail.com
website: https://github.com/Hedlen

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  hedlen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: balazssandor
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links (https://fontawesome.com/icons?d=gallery&m=free)
additional_links:
- title: google scholar
  icon: fab fa-google
  url: https://scholar.google.com/citations?user=vwVneW4AAAAJ&hl=zh-CN

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Biography
about_profile_image: images/white_bg.png
about_content: | # this will include new lines to allow paragraphs
  I received my Master degree at Information and Communication Engineering in University of Electronic Science and Technology of China (UESTC), supervised by 
  [Prof. Yiming Pi](https://www.researchgate.net/scientific-contributions/Yiming-Pi-13739828) and 
  [Prof. Zongjie Cao](https://www.researchgate.net/scientific-contributions/Zongjie-Cao-33269443), in 2019. I obtained my Bachelor degree at Electronic Information Engineering in University of South China (USC) in 2015.
  During in internship, i was luckily mentored by [Dr. Zhanghui Kuang](https://scholar.google.com/citations?hl=zh-CN&user=z4wkHDgAAAAJ) at SenseTime and [Prof. Shuaicheng Liu](http://www.liushuaicheng.org/), [Dr. Jue Wang](https://juew.org/) at MEGVII Research since 2018. I am a Full time computer vision researcher at present in MEGVII Research. My research interests include Computer Vision & Computer Graphics.
  
content:
  - title: Education & Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:      
      - layout: left
        title: M.Sc.
        # link: grubhub.com
        # link_text: grubhub.com
        # sub_title: 
        caption: Sept. 2016 - Jul. 2019
        description: | # this will include new lines to allow paragraphs
            ## **University of Electronic Science and Technology of China (UESTC)**
            Information and Communication Engineering <br />
            <mark>Thesis</mark> Target recognition, Target detection, Model compression.
      
      - layout: left
        title: B.E.
        # link: bmwgroup.com
        # link_text: bmwgroup.com
        # sub_title:  
        caption: Sept. 2011 - Jul. 2015
        description: | # this will include new lines to allow paragraphs
            
            ## **University of South China (USC)**
            Electronic Information Engineering <br />
            <mark>Thesis</mark> Electronic circuit system. 
                     
      - layout: left
        title: Internship
        # link: www.msg.group
        # link_text: msg.group
        # sub_title: 
        caption: May. 2018 - Dec. 2018
        description: | # this will include new lines to allow paragraphs
          ## **SenseTime Research**
          Intern <br />
          <mark>Feilds</mark> Face recognition and detection, Image and video retrieval.

      - layout: left
        title: Internship
        # link: www.msg.group
        # link_text: msg.group
        # sub_title: 
        caption:  Dec. 2018 - Jul. 2019
        description: | # this will include new lines to allow paragraphs
          ## **Megvii Research**
          Intern <br />
          <mark>Feilds</mark>  Autonomous driving, Intelligent cockpit, Behavior detection.
      
      - layout: left
        title: Researcher
        # link: www.msg.group
        # link_text: msg.group
        # sub_title: 
        caption:  Jul. 2019 - Present
        description: | # this will include new lines to allow paragraphs
          ## **Megvii Research**
          Algorithm Leader <br />
          <mark>Feilds</mark> There are currently 10 members in the team. The main direction is related to computer graphics, 
          including High dynamic range image, Image enhancement, Noise reduction, Image alignment, Deghosting, Super-resolution etc.
            
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CVPR 2022
        # caption: 
        sub_title: <blue_mark>Under review</blue_mark>
        description: | # this will include new lines to allow paragraphs
          ## **HDRLUT: Unsupervised Learning 1D Lookup Tables for High Dynamic Range Imaging**
          **Ting Jiang**, Chuan Wang, Xinpeng Li, Haoqiang Fan, Shuaicheng Liu
      
      - layout: left
        title: TIP 2022
        # caption: 
        sub_title: <blue_mark>Under review</blue_mark>
        description: | # this will include new lines to allow paragraphs
          ## **Efficient Neural Architecture Search via firefly optimization for SAR ship detection**
          Jielei Wang, **Ting Jiang**, Zongyong Cui, Changjie Cao, Zongjie Cao

      - layout: left
        title: CVPRW 2021
        # caption: 
        sub_title: <blue_mark>Accepted, The winning method of the first edition of NTIRE2021 Multi-Frame HDR Challenge</blue_mark>
        description: | # this will include new lines to allow paragraphs
          ## **ADNet: Attention-guided deformable convolutional network for high dynamic range imaging**
          Zhen Liu, Wenjie Lin, Xinpeng Li, **Ting Jiang**, Mingyan Han, Qing Rao, Haoqiang Fan, Jian Sun, Shuaicheng Liu  
          [[PDF](https://openaccess.thecvf.com/content/CVPR2021W/NTIRE/papers/Liu_ADNet_Attention-Guided_Deformable_Convolutional_Network_for_High_Dynamic_Range_Imaging_CVPRW_2021_paper.pdf)]
          [[Github](https://github.com/liuzhen03/ADNet)]
          [Video: [Youtube](https://www.youtube.com/watch?v=M0X-BXe3UqM&t=2s), [Bilibili](https://www.bilibili.com/video/BV19h411a78M/)]
          [[BibTex](http://www.liushuaicheng.org/bibtex/CVPR21_ADNet.bib)]
      
      - layout: left
        title: Neuro Computing 2021
        # caption: 
        sub_title: <blue_mark>Accepted</blue_mark>
        description: | # this will include new lines to allow paragraphs
          ## **Filter pruning with a feature map entropy importance criterion for convolution neural networks compressing**
          Jielei Wang, **Ting Jiang**, Zongyong Cui, Zongjie Cao  
          [[PDF](https://www.sciencedirect.com/science/article/abs/pii/S092523122101078X)]
          [[BibTex](https://scholar.googleusercontent.com/scholar.bib?q=info:W5Y6IjacCXMJ:scholar.google.com/&output=citation&scisdr=CgX7dAiIEPLblS6f6f0:AAGBfm0AAAAAYaiZ8f3mBG7uSNMy8SQbSmkDPpRR3XC3&scisig=AAGBfm0AAAAAYaiZ8Ws0rRq80UAZsZNInzQYHjniOy4y&scisf=4&ct=citation&cd=-1&hl=zh-CN)]
      
      - layout: left
        title: IGARSS 2018
        # caption: 
        sub_title: <blue_mark>Accepted</blue_mark>
        description: | # this will include new lines to allow paragraphs
          ## **Data augmentation with Gabor filter in deep convolutional neural networks for SAR target recognition**
          **Ting Jiang**, Zongyong Cui, Zhi Zhou, Zongjie Cao  
          [[PDF](https://sci-hub.se/https://ieeexplore.ieee.org/document/8518792)]
          [[BibTex](https://scholar.googleusercontent.com/scholar.bib?q=info:HRfCTYzKoHEJ:scholar.google.com/&output=citation&scisdr=CgX3wfUqEPLblTZ_Te4:AAGBfm0AAAAAYbB5Ve7zKKgIjF-o89gQhHd_TF32yaLA&scisig=AAGBfm0AAAAAYbB5VVN2mVrRg7Mctytlrqk1zDiJZ6Q4&scisf=4&ct=citation&cd=-1&hl=zh-CN)]
      
      - layout: left
        title: IGARSS 2018
        # caption: 
        sub_title: <blue_mark>Accepted</blue_mark>
        description: | # this will include new lines to allow paragraphs
          ## **Adaptive Weighted Multi-Task Sparse Representation Classification in SAR Image Recognition**
          Zhi Zhou, Zongjie Cao, Yiming Pi, **Ting Jiang**  
          [[PDF](https://sci-hub.se/10.1109/igarss.2018.8519004)]
          [[BibTex](https://scholar.googleusercontent.com/scholar.bib?q=info:f_rOmrAJfqoJ:scholar.google.com/&output=citation&scisdr=CgX3wfUqEPLblTZ_1A4:AAGBfm0AAAAAYbB5zA7JsuImgF6RjVMo4zr94VpXrOVu&scisig=AAGBfm0AAAAAYbB5zC7GmB-jc-_X80TEdD3WwGNkLsfp&scisf=4&ct=citation&cd=-1&hl=zh-CN)]

      

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Driver Monitor System
        caption: Dec. 2018 - Jul. 2019
        sub_title: Major member
        description: | # this will include new lines to allow paragraphs
          I am responsible for designing a light-weighted end-to-end network running on an onboard chip to detect smoking, phoning, 
          and drinking in driving. Participated in the overall pipeline of algorithm development, including data collection, 
          data cleaning, algorithm development, and upgrading.
        video_path: images/DMS_smoke_demo1.mp4
        video_path1: images/DMS_smoke_demo2.mp4
        video_path2: images/DMS_phone_demo.mp4

      - layout: left
        title: High dynaimc range image
        caption: Jul. 2019 - Present
        sub_title: Algorithm Leader
        description: | # this will include new lines to allow paragraphs
          High-Dynamic Range (HDR) image, compared with ordinary images, can provide more dynamic range and image details, according to different exposure time Low-Dynamic Range(LDR) images, 
          use each exposure Time corresponds to the LDR image with the best details to synthesize the final HDR image, which can better reflect the visual effects in the real environment of people.
        img_path: images/HDR.png
        img_path1: images/HDR1.png
        img_path2: images/HDR2.png

        - layout: left
        title: Portrait beauty
        caption: Jul. 2019 - Present
        sub_title: Algorithm Leader
        description: | # this will include new lines to allow paragraphs
          Adjust the face area adaptively to achieve the effect of beautifying portraits. 
          As a team leader, lead team members to develop a new type of beautifying algorithm, and successfully applied to products and widely used.
        img_path: images/b.png
        img_path1: images/b1.png
        img_path2: images/b2.png

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
theme: jekyll-theme-architect